/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

'use server'

import { b } from '../index';
import type { Check, Checked  } from "../types";
import type { Image, Audio, Pdf, Video } from "@boundaryml/baml";

import type {  Await,  Calculation,  ClarificationRequest,  DoneForNow,  IntentCalculate,  IntentCommentOnIssue,  IntentCreateTicket,  IntentLinkIssues,  IntentSearchGitHub,  IntentUpdateGitHubIssue,  NothingToDo } from "../types"

import type * as types from "../types"

/**
 * Regular BAML server actions that return direct responses.
 */

/**
 * Executes the "DetermineNextStep" BAML action.
 *
 * This server action calls the underlying BAML function "DetermineNextStep"
 * with the specified parameters.
 *
 * @param { string } thread - Input parameter.
 *
 * @returns {Promise<types.ClarificationRequest | types.DoneForNow | types.NothingToDo | types.Await | types.IntentCreateTicket | types.IntentSearchGitHub | types.IntentUpdateGitHubIssue | types.IntentCommentOnIssue | types.IntentLinkIssues>} A promise that resolves with the result of the action.
 */
export const DetermineNextStep = async (
  thread: string,
): Promise<types.ClarificationRequest | types.DoneForNow | types.NothingToDo | types.Await | types.IntentCreateTicket | types.IntentSearchGitHub | types.IntentUpdateGitHubIssue | types.IntentCommentOnIssue | types.IntentLinkIssues> => {
  return b.DetermineNextStep(
    thread,
  );
};

/**
 * Executes the "SquashResponseContext" BAML action.
 *
 * This server action calls the underlying BAML function "SquashResponseContext"
 * with the specified parameters.
 *
 * @param { string } thread - Input parameter.
 * @param { string } error - Input parameter.
 *
 * @returns {Promise<string>} A promise that resolves with the result of the action.
 */
export const SquashResponseContext = async (
  thread: string,
  error: string,
): Promise<string> => {
  return b.SquashResponseContext(
    thread,
    error,
  );
};