/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Audio, Image, Pdf, Video } from "@boundaryml/baml";
import type { partial_types } from "../partial_types";
import type * as types from "../types";
import type {
	Await,
	Calculation,
	Check,
	Checked,
	ClarificationRequest,
	DoneForNow,
	IntentCalculate,
	NothingToDo,
} from "../types";

export type StreamingServerTypes = {
	DetermineNextStep:
		| ClarificationRequest
		| DoneForNow
		| IntentCalculate
		| NothingToDo
		| Await;
	PerformCalculation: Calculation;
	SquashResponseContext: string;
};
